package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"strings"
)

const generatedHeader = "// Code generated by autodi, DO NOT EDIT.\n\n"

// GeneratedFile represents a file to be written.
type GeneratedFile struct {
	Name    string
	Content []byte
}

// CodeGen orchestrates code generation.
type CodeGen struct {
	cfg        *Config
	graph      *Graph
	commands   []*DiscoveredCommand
	moduleRoot string
	imports    *ImportManager
}

// NewCodeGen creates a code generator.
func NewCodeGen(cfg *Config, graph *Graph, commands []*DiscoveredCommand, moduleRoot string) *CodeGen {
	return &CodeGen{
		cfg:        cfg,
		graph:      graph,
		commands:   commands,
		moduleRoot: moduleRoot,
		imports:    NewImportManager(),
	}
}

// Generate produces the main.go file, an interactive DI diagram, and a package diagram.
func (cg *CodeGen) Generate() ([]GeneratedFile, error) {
	f, err := cg.generateMain()
	if err != nil {
		return nil, err
	}
	diGraph := GeneratedFile{
		Name:    "dependency-graph.html",
		Content: renderDIHTML(cg.graph, cg.commands, cg.cfg),
	}

	pkgContent, err := generatePkgDiagram(cg.cfg, cg.moduleRoot)
	if err != nil {
		pkgContent = []byte(fmt.Sprintf(
			"<html><body><pre>autodi: package diagram failed: %v</pre></body></html>", err))
	}
	pkgDiag := GeneratedFile{
		Name:    "package-diagram.html",
		Content: pkgContent,
	}

	return []GeneratedFile{f, diGraph, pkgDiag}, nil
}

// generateMain generates the complete main.go with two-phase DI.
func (cg *CodeGen) generateMain() (GeneratedFile, error) {
	cg.imports.Reset()

	// Pre-register cmd package imports with predictable aliases
	cmdAliases := make(map[string]string) // pkgPath → alias
	for _, cmd := range cg.commands {
		alias := cmd.PkgName + "cmd"
		cmdAliases[cmd.PkgPath] = cg.imports.AddWithAlias(cmd.PkgPath, alias)
	}

	// We'll build the main function body and init functions separately,
	// then combine them. First, generate all init functions to discover imports.
	var initBuf bytes.Buffer
	for _, cmd := range cg.commands {
		if !cmd.HasDeps() {
			continue
		}
		if err := cg.generateInitFunc(&initBuf, cmd, cmdAliases[cmd.PkgPath]); err != nil {
			return GeneratedFile{}, fmt.Errorf("generate init for %s: %w", cmd.Name, err)
		}
		initBuf.WriteString("\n")
	}

	// Now generate the main function
	var mainBuf bytes.Buffer

	// main function
	cg.imports.Add("os", "os")
	cobraQualifier := cg.imports.Add("github.com/spf13/cobra", "cobra")

	mainBuf.WriteString("func main() {\n")

	// Root command
	fmt.Fprintf(&mainBuf, "\troot := &%s.Command{Use: %q, Short: %q", cobraQualifier, cg.cfg.AppName, cg.cfg.AppShort)
	if cg.cfg.AppLong != "" {
		fmt.Fprintf(&mainBuf, ", Long: %q", cg.cfg.AppLong)
	}
	mainBuf.WriteString("}\n\n")

	// Init function map (for DI commands)
	hasDI := false
	for _, cmd := range cg.commands {
		if cmd.HasDeps() {
			hasDI = true
			break
		}
	}

	if hasDI {
		fmt.Fprintf(&mainBuf, "\ttype initFunc func(cmd, top *%s.Command) (func(), error)\n", cobraQualifier)
		fmt.Fprintf(&mainBuf, "\tinitFuncs := make(map[*%s.Command]initFunc)\n\n", cobraQualifier)
	}

	// Register all commands
	for _, cmd := range cg.commands {
		alias := cmdAliases[cmd.PkgPath]
		exportName := cmdExportName(cmd.Name)

		// Generate zero-value args for constructor
		var zeroArgs []string
		for _, param := range cmd.Params {
			zeroArgs = append(zeroArgs, zeroValueForType(param.Type))
		}

		mainBuf.WriteString("\t{\n")
		fmt.Fprintf(&mainBuf, "\t\tstub := %s.%s(%s)\n", alias, cmd.FuncName, strings.Join(zeroArgs, ", "))

		if cmd.IsSingle {
			// Single command: Command() + direct RunE → Handle
			mainBuf.WriteString("\t\tcmd := stub.Command()\n")
			fmt.Fprintf(&mainBuf, "\t\tcmd.RunE = func(c *%s.Command, _ []string) error { return stub.Handle(c) }\n", cobraQualifier)
			mainBuf.WriteString("\t\troot.AddCommand(cmd)\n")
			if cmd.HasDeps() {
				fmt.Fprintf(&mainBuf, "\t\tinitFuncs[cmd] = init%s\n", exportName)
			}
		} else {
			// Multi-subcommand: Command() + wireRunE for each handler
			mainBuf.WriteString("\t\ttree := stub.Command()\n")
			for _, h := range cmd.Handlers {
				cmdName := pascalToKebab(h.MethodName)
				fmt.Fprintf(&mainBuf, "\t\twireRunE(tree, %q, stub.%s)\n", cmdName, h.MethodName)
			}
			mainBuf.WriteString("\t\troot.AddCommand(tree)\n")
			if cmd.HasDeps() {
				fmt.Fprintf(&mainBuf, "\t\tinitFuncs[tree] = init%s\n", exportName)
			}
		}

		mainBuf.WriteString("\t}\n")
	}

	// PersistentPreRunE / PostRunE
	if hasDI {
		mainBuf.WriteString("\n\tvar cleanup func()\n")
		fmt.Fprintf(&mainBuf, "\troot.PersistentPreRunE = func(cmd *%s.Command, args []string) error {\n", cobraQualifier)
		mainBuf.WriteString("\t\ttop := cmd\n")
		mainBuf.WriteString("\t\tfor top.HasParent() && top.Parent().HasParent() {\n")
		mainBuf.WriteString("\t\t\ttop = top.Parent()\n")
		mainBuf.WriteString("\t\t}\n")
		mainBuf.WriteString("\t\tif fn, ok := initFuncs[top]; ok {\n")
		mainBuf.WriteString("\t\t\tvar err error\n")
		mainBuf.WriteString("\t\t\tcleanup, err = fn(cmd, top)\n")
		mainBuf.WriteString("\t\t\treturn err\n")
		mainBuf.WriteString("\t\t}\n")
		mainBuf.WriteString("\t\treturn nil\n")
		mainBuf.WriteString("\t}\n")
		fmt.Fprintf(&mainBuf, "\troot.PersistentPostRunE = func(cmd *%s.Command, args []string) error {\n", cobraQualifier)
		mainBuf.WriteString("\t\tif cleanup != nil {\n")
		mainBuf.WriteString("\t\t\tcleanup()\n")
		mainBuf.WriteString("\t\t}\n")
		mainBuf.WriteString("\t\treturn nil\n")
		mainBuf.WriteString("\t}\n")
	}

	mainBuf.WriteString("\n\tif err := root.Execute(); err != nil {\n")
	fmt.Fprintf(&mainBuf, "\t\tos.Exit(1)\n")
	mainBuf.WriteString("\t}\n")
	mainBuf.WriteString("}\n")

	// Generate helper functions
	var helperBuf bytes.Buffer

	// wireRunE — always needed (all commands use it for handler wiring)
	cg.imports.Add("strings", "strings")
	helperBuf.WriteString("// wireRunE connects a handler method to a subcommand's RunE by kebab-case name.\n")
	helperBuf.WriteString("// For nested commands, the name segments form a path (e.g. \"pool-list\" matches pool→list).\n")
	fmt.Fprintf(&helperBuf, "func wireRunE(parent *%s.Command, name string, handler func(*%s.Command) error) {\n", cobraQualifier, cobraQualifier)
	helperBuf.WriteString("\t// Try exact match first (direct child)\n")
	helperBuf.WriteString("\tfor _, sub := range parent.Commands() {\n")
	helperBuf.WriteString("\t\tif sub.Name() == name {\n")
	helperBuf.WriteString("\t\t\th := handler\n")
	fmt.Fprintf(&helperBuf, "\t\t\tsub.RunE = func(cmd *%s.Command, _ []string) error { return h(cmd) }\n", cobraQualifier)
	helperBuf.WriteString("\t\t\treturn\n")
	helperBuf.WriteString("\t\t}\n")
	helperBuf.WriteString("\t}\n")
	helperBuf.WriteString("\t// Try path-based match: split name by \"-\" and greedily match child commands\n")
	helperBuf.WriteString("\tparts := strings.Split(name, \"-\")\n")
	helperBuf.WriteString("\twireRunEPath(parent, parts, handler)\n")
	helperBuf.WriteString("}\n\n")

	fmt.Fprintf(&helperBuf, "func wireRunEPath(parent *%s.Command, parts []string, handler func(*%s.Command) error) bool {\n", cobraQualifier, cobraQualifier)
	helperBuf.WriteString("\tif len(parts) == 0 {\n")
	helperBuf.WriteString("\t\treturn false\n")
	helperBuf.WriteString("\t}\n")
	helperBuf.WriteString("\t// Try progressively longer prefixes as the child command name\n")
	helperBuf.WriteString("\tfor i := 1; i <= len(parts); i++ {\n")
	helperBuf.WriteString("\t\tcandidate := strings.Join(parts[:i], \"-\")\n")
	helperBuf.WriteString("\t\tfor _, sub := range parent.Commands() {\n")
	helperBuf.WriteString("\t\t\tif sub.Name() != candidate {\n")
	helperBuf.WriteString("\t\t\t\tcontinue\n")
	helperBuf.WriteString("\t\t\t}\n")
	helperBuf.WriteString("\t\t\tif i == len(parts) {\n")
	helperBuf.WriteString("\t\t\t\t// Leaf match\n")
	helperBuf.WriteString("\t\t\t\th := handler\n")
	fmt.Fprintf(&helperBuf, "\t\t\t\tsub.RunE = func(cmd *%s.Command, _ []string) error { return h(cmd) }\n", cobraQualifier)
	helperBuf.WriteString("\t\t\t\treturn true\n")
	helperBuf.WriteString("\t\t\t}\n")
	helperBuf.WriteString("\t\t\t// Try remaining parts as deeper path\n")
	helperBuf.WriteString("\t\t\tif wireRunEPath(sub, parts[i:], handler) {\n")
	helperBuf.WriteString("\t\t\t\treturn true\n")
	helperBuf.WriteString("\t\t\t}\n")
	helperBuf.WriteString("\t\t}\n")
	helperBuf.WriteString("\t}\n")
	helperBuf.WriteString("\treturn false\n")
	helperBuf.WriteString("}\n")

	// swapRunE + relativePath — only needed for DI commands
	if hasDI {
		helperBuf.WriteString("\n// swapRunE replaces the executing command's RunE with the real one from the DI-built tree.\n")
		fmt.Fprintf(&helperBuf, "func swapRunE(executing, stubTop, realTop *%s.Command) {\n", cobraQualifier)
		helperBuf.WriteString("\tpath := relativePath(executing, stubTop)\n")
		helperBuf.WriteString("\ttarget := realTop\n")
		helperBuf.WriteString("\tfor _, name := range path {\n")
		helperBuf.WriteString("\t\tfor _, sub := range target.Commands() {\n")
		helperBuf.WriteString("\t\t\tif sub.Name() == name {\n")
		helperBuf.WriteString("\t\t\t\ttarget = sub\n")
		helperBuf.WriteString("\t\t\t\tbreak\n")
		helperBuf.WriteString("\t\t\t}\n")
		helperBuf.WriteString("\t\t}\n")
		helperBuf.WriteString("\t}\n")
		helperBuf.WriteString("\texecuting.RunE = target.RunE\n")
		helperBuf.WriteString("}\n\n")
		fmt.Fprintf(&helperBuf, "func relativePath(cmd, ancestor *%s.Command) []string {\n", cobraQualifier)
		helperBuf.WriteString("\tif cmd == ancestor {\n")
		helperBuf.WriteString("\t\treturn nil\n")
		helperBuf.WriteString("\t}\n")
		helperBuf.WriteString("\treturn append(relativePath(cmd.Parent(), ancestor), cmd.Name())\n")
		helperBuf.WriteString("}\n")
	}

	// Combine everything
	var full bytes.Buffer
	full.WriteString(generatedHeader)
	full.WriteString("package main\n\n")
	full.WriteString(cg.imports.FormatBlock())
	full.WriteString("\n")
	full.Write(mainBuf.Bytes())
	full.WriteString("\n")
	full.Write(initBuf.Bytes())
	if helperBuf.Len() > 0 {
		full.WriteString("\n")
		full.Write(helperBuf.Bytes())
	}

	src, err := format.Source(full.Bytes())
	if err != nil {
		return GeneratedFile{Name: "main.go", Content: full.Bytes()},
			fmt.Errorf("format main.go: %w\n--- source ---\n%s", err, full.String())
	}

	return GeneratedFile{Name: "main.go", Content: src}, nil
}

// autoCollectParam records an auto-collected slice parameter.
type autoCollectParam struct {
	idx       int
	elemType  string      // element type string (e.g., "github.com/.../seed.Seeder")
	providers []*Provider // collected providers
}

// generateInitFunc generates an init<Cmd> function for a DI command.
// It uses the foundation container for dependency resolution.
func (cg *CodeGen) generateInitFunc(buf *bytes.Buffer, cmd *DiscoveredCommand, cmdAlias string) error {
	exportName := cmdExportName(cmd.Name)
	cobraQualifier := cg.imports.Add("github.com/spf13/cobra", "cobra")
	containerQualifier := cg.imports.Add(cg.cfg.Module+"/pkg/foundation/container", "container")

	// ---- Phase 1: Discovery (unchanged) ----

	var neededTypes []string
	var groupParams []struct {
		idx       int
		groupName string
	}
	var autoParams []autoCollectParam

	for i, param := range cmd.Params {
		groupName := cg.matchGroup(param.TypeStr)
		if groupName != "" {
			groupParams = append(groupParams, struct {
				idx       int
				groupName string
			}{i, groupName})
			for _, p := range cg.graph.Groups[groupName] {
				for _, dep := range p.Params {
					neededTypes = append(neededTypes, dep.TypeStr)
				}
			}
		} else if strings.HasPrefix(param.TypeStr, "[]") {
			elemType := param.TypeStr[2:]
			autoProviders := cg.graph.AutoCollect(elemType)
			if len(autoProviders) > 0 {
				autoParams = append(autoParams, autoCollectParam{
					idx:       i,
					elemType:  elemType,
					providers: autoProviders,
				})
				for _, p := range autoProviders {
					for _, dep := range p.Params {
						neededTypes = append(neededTypes, dep.TypeStr)
					}
				}
			} else {
				neededTypes = append(neededTypes, param.TypeStr)
			}
		} else {
			neededTypes = append(neededTypes, param.TypeStr)
		}
	}

	providers, err := cg.graph.ProvidersForTypes(neededTypes)
	if err != nil {
		return fmt.Errorf("resolve deps for %s: %w", cmd.Name, err)
	}

	// Deep auto-collection
	deepAutoMap := make(map[string][]autoCollectParam)
	needsResolve := false
	for _, p := range providers {
		for i, param := range p.Params {
			if !strings.HasPrefix(param.TypeStr, "[]") {
				continue
			}
			if cg.matchGroup(param.TypeStr) != "" {
				continue
			}
			elemType := param.TypeStr[2:]
			autoProviders := cg.graph.AutoCollect(elemType)
			if len(autoProviders) > 0 {
				key := p.PkgPath + "." + p.FuncName
				deepAutoMap[key] = append(deepAutoMap[key], autoCollectParam{
					idx:       i,
					elemType:  elemType,
					providers: autoProviders,
				})
				for _, ap := range autoProviders {
					for _, dep := range ap.Params {
						neededTypes = append(neededTypes, dep.TypeStr)
					}
				}
				needsResolve = true
			}
		}
	}

	if needsResolve {
		extraEdges := make(map[string][]string)
		for _, p := range providers {
			key := p.PkgPath + "." + p.FuncName
			aps, ok := deepAutoMap[key]
			if !ok {
				continue
			}
			for _, ret := range p.Returns {
				for _, ap := range aps {
					for _, cp := range ap.providers {
						for _, dep := range cp.Params {
							extraEdges[ret.TypeStr] = append(extraEdges[ret.TypeStr], dep.TypeStr)
						}
					}
				}
			}
		}
		providers, err = cg.graph.ProvidersForTypesWithExtraEdges(neededTypes, extraEdges)
		if err != nil {
			return fmt.Errorf("resolve deps for %s (after auto-collect): %w", cmd.Name, err)
		}
	}

	// Collect all auto-collected providers (command-level + deep) for registration
	allAutoProviders := make(map[string]*Provider) // deduplicate by key
	for _, ap := range autoParams {
		for _, p := range ap.providers {
			allAutoProviders[p.PkgPath+"."+p.FuncName] = p
		}
	}
	for _, aps := range deepAutoMap {
		for _, ap := range aps {
			for _, p := range ap.providers {
				allAutoProviders[p.PkgPath+"."+p.FuncName] = p
			}
		}
	}

	// Group providers also need registration
	var groupProvidersList []*Provider
	for _, gp := range groupParams {
		groupProvidersList = append(groupProvidersList, cg.graph.Groups[gp.groupName]...)
	}

	// Pre-register imports
	cg.registerProviderImports(providers)
	for _, p := range allAutoProviders {
		_ = cg.qualifyFunc(p)
	}
	cg.registerProviderImports(groupProvidersList)

	// ---- Phase 2: Container-based code generation ----

	fmt.Fprintf(buf, "func init%s(cmd, top *%s.Command) (func(), error) {\n", exportName, cobraQualifier)
	fmt.Fprintf(buf, "\tapp := %s.NewApplication()\n\n", containerQualifier)

	// Register all singleton providers
	registered := make(map[string]bool) // deduplicate by key
	for _, p := range providers {
		key := p.PkgPath + "." + p.FuncName
		if registered[key] {
			continue
		}
		registered[key] = true
		qualifier := cg.qualifyFunc(p)
		fmt.Fprintf(buf, "\tapp.Singleton(%s)\n", qualifier)
	}

	// Register auto-collected providers (if not already registered)
	for _, p := range allAutoProviders {
		key := p.PkgPath + "." + p.FuncName
		if registered[key] {
			continue
		}
		registered[key] = true
		qualifier := cg.qualifyFunc(p)
		fmt.Fprintf(buf, "\tapp.Singleton(%s)\n", qualifier)
	}

	// Register group providers (if not already registered)
	for _, p := range groupProvidersList {
		key := p.PkgPath + "." + p.FuncName
		if registered[key] {
			continue
		}
		registered[key] = true
		qualifier := cg.qualifyFunc(p)
		fmt.Fprintf(buf, "\tapp.Singleton(%s)\n", qualifier)
	}

	buf.WriteString("\n")

	// Build the Invoke closure parameter list:
	// 1. Command constructor params (non-slice params resolved by type)
	// 2. Closeable types needed for cleanup
	// 3. Auto-collected concrete types (for building slices)
	// 4. Group concrete types (for building slices)

	usedVars := make(map[string]bool)
	varMap := make(map[string]string) // typeStr → param name in Invoke closure

	type invokeParam struct {
		varName string
		typeStr string // fully qualified
	}
	var invokeParams []invokeParam

	// Helper to add a type to the invoke params (deduplicated)
	addInvokeParam := func(typeStr string) string {
		if v, ok := varMap[typeStr]; ok {
			return v
		}
		fieldName := FieldName(typeStr)
		varName := localVarName(fieldName)
		if cg.imports.IsQualifier(varName) {
			varName = varName + "Svc"
		}
		varName = cg.uniqueLocalVar(varName, usedVars)
		varMap[typeStr] = varName
		invokeParams = append(invokeParams, invokeParam{varName: varName, typeStr: typeStr})
		return varName
	}

	// Add command constructor params (non-slice)
	for _, param := range cmd.Params {
		if strings.HasPrefix(param.TypeStr, "[]") {
			continue // slices are built from auto-collected/group providers
		}
		resolved := cg.graph.resolveType(param.TypeStr)
		addInvokeParam(resolved)
		// Also map the original type
		if resolved != param.TypeStr {
			varMap[param.TypeStr] = varMap[resolved]
		}
	}

	// Add auto-collected concrete types
	for _, ap := range autoParams {
		for _, p := range ap.providers {
			for _, ret := range p.Returns {
				addInvokeParam(ret.TypeStr)
			}
		}
	}

	// Add deep auto-collected concrete types
	for _, aps := range deepAutoMap {
		for _, ap := range aps {
			for _, p := range ap.providers {
				for _, ret := range p.Returns {
					addInvokeParam(ret.TypeStr)
				}
			}
		}
	}

	// Add group concrete types
	for _, p := range groupProvidersList {
		for _, ret := range p.Returns {
			addInvokeParam(ret.TypeStr)
		}
	}

	// Add closeable types from ALL providers (for cleanup)
	var closeables []CloseableField
	for _, p := range providers {
		for _, ret := range p.Returns {
			if isNilable(ret.Type) {
				varName := addInvokeParam(ret.TypeStr)
				if cl := checkCloseable(ret.Type, varName); cl != nil {
					closeables = append(closeables, *cl)
				}
			}
		}
	}

	// Generate the Invoke call
	buf.WriteString("\tvar cleanup func()\n")
	fmt.Fprintf(buf, "\terr := app.Invoke(func(\n")
	for _, ip := range invokeParams {
		shortType := cg.shortType(ip.typeStr)
		fmt.Fprintf(buf, "\t\t%s %s,\n", ip.varName, shortType)
	}
	buf.WriteString("\t) {\n")

	// Inside the closure: build auto-collected slices
	for _, ap := range autoParams {
		ifaceType := cg.shortType(ap.elemType)
		sliceVarName := deriveSliceVarName(ap.elemType)
		sliceVarName = cg.uniqueLocalVar(sliceVarName, usedVars)

		fmt.Fprintf(buf, "\t\t%s := []%s{", sliceVarName, ifaceType)
		for j, p := range ap.providers {
			if j > 0 {
				buf.WriteString(", ")
			}
			// Find the var name for this provider's return type
			for _, ret := range p.Returns {
				if v, ok := varMap[ret.TypeStr]; ok {
					buf.WriteString(v)
					break
				}
			}
		}
		buf.WriteString("}\n")
		varMap[cmd.Params[ap.idx].TypeStr] = sliceVarName
	}

	// Build deep auto-collected slices for providers that need them
	// (These are consumed by providers, not by the command directly.
	//  With the container, the provider constructor receives them via dig.
	//  But since we're not using dig.Group, we need a different approach.)
	// For deep auto-collect: the provider that takes []Interface is already
	// registered as Singleton. But dig can't auto-collect into slices.
	// We need to provide the slice manually.
	for provKey, aps := range deepAutoMap {
		for _, ap := range aps {
			ifaceType := cg.shortType(ap.elemType)
			sliceVarName := deriveSliceVarName(ap.elemType) + "Deep"
			sliceVarName = cg.uniqueLocalVar(sliceVarName, usedVars)

			fmt.Fprintf(buf, "\t\t%s := []%s{", sliceVarName, ifaceType)
			for j, p := range ap.providers {
				if j > 0 {
					buf.WriteString(", ")
				}
				for _, ret := range p.Returns {
					if v, ok := varMap[ret.TypeStr]; ok {
						buf.WriteString(v)
						break
					}
				}
			}
			buf.WriteString("}\n")
			_ = provKey // used for tracking only
		}
	}

	// Build group slices
	for _, gp := range groupParams {
		groupProviders := cg.graph.Groups[gp.groupName]
		if len(groupProviders) == 0 {
			continue
		}
		groupCfg := cg.cfg.Groups[gp.groupName]
		ifaceType := cg.qualifyType(groupCfg.Interface, "")
		groupVarName := localVarName(GroupFieldName(gp.groupName))
		groupVarName = cg.uniqueLocalVar(groupVarName, usedVars)

		fmt.Fprintf(buf, "\t\t%s := []%s{", groupVarName, ifaceType)
		for j, p := range groupProviders {
			if j > 0 {
				buf.WriteString(", ")
			}
			for _, ret := range p.Returns {
				if v, ok := varMap[ret.TypeStr]; ok {
					buf.WriteString(v)
					break
				}
			}
		}
		buf.WriteString("}\n")
		varMap[cmd.Params[gp.idx].TypeStr] = groupVarName
	}

	// Build NewCommand args
	var newCmdArgs []string
	for _, param := range cmd.Params {
		if varName, ok := varMap[param.TypeStr]; ok {
			newCmdArgs = append(newCmdArgs, varName)
		} else {
			resolved := cg.graph.resolveType(param.TypeStr)
			if varName, ok := varMap[resolved]; ok {
				newCmdArgs = append(newCmdArgs, varName)
			} else {
				newCmdArgs = append(newCmdArgs, "nil /* unresolved: "+toShortTypeName(param.TypeStr)+" */")
			}
		}
	}

	// Create real command instance and wire handlers
	fmt.Fprintf(buf, "\n\t\treal := %s.%s(%s)\n", cmdAlias, cmd.FuncName, strings.Join(newCmdArgs, ", "))

	if cmd.IsSingle {
		cobraQ := cg.imports.Add("github.com/spf13/cobra", "cobra")
		fmt.Fprintf(buf, "\t\trealCmd := real.Command()\n")
		fmt.Fprintf(buf, "\t\trealCmd.RunE = func(c *%s.Command, _ []string) error { return real.Handle(c) }\n", cobraQ)
		fmt.Fprintf(buf, "\t\tswapRunE(cmd, top, realCmd)\n")
	} else {
		fmt.Fprintf(buf, "\t\ttree := real.Command()\n")
		for _, h := range cmd.Handlers {
			cmdName := pascalToKebab(h.MethodName)
			fmt.Fprintf(buf, "\t\twireRunE(tree, %q, real.%s)\n", cmdName, h.MethodName)
		}
		fmt.Fprintf(buf, "\t\tswapRunE(cmd, top, tree)\n")
	}

	// Generate cleanup inside closure
	if len(closeables) > 0 {
		buf.WriteString("\n\t\tcleanup = func() {\n")
		for i := len(closeables) - 1; i >= 0; i-- {
			cl := closeables[i]
			if cl.HasCtx {
				cg.imports.Add("context", "context")
				fmt.Fprintf(buf, "\t\t\tif %s != nil {\n\t\t\t\t%s.%s(context.Background())\n\t\t\t}\n", cl.VarName, cl.VarName, cl.Method)
			} else {
				fmt.Fprintf(buf, "\t\t\tif %s != nil {\n\t\t\t\t%s.%s()\n\t\t\t}\n", cl.VarName, cl.VarName, cl.Method)
			}
		}
		buf.WriteString("\t\t}\n")
	}

	buf.WriteString("\t})\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil, err\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn cleanup, nil\n")
	buf.WriteString("}\n")

	return nil
}

// writeLocalProviderCall writes a provider call using local variables.
func (cg *CodeGen) writeLocalProviderCall(buf *bytes.Buffer, p *Provider, varMap map[string]string, usedVars map[string]bool, closeables *[]CloseableField, consumedTypes map[string]bool) {
	qualifier := cg.qualifyFunc(p)
	args := cg.buildLocalArgs(p, varMap)

	// Determine local var names for return types
	var lhsNames []string
	for _, ret := range p.Returns {
		// Check if this return type is actually consumed
		isConsumed := consumedTypes[ret.TypeStr]
		if !isConsumed {
			// Also check via bindings
			for ifaceStr := range consumedTypes {
				if cg.graph.resolveType(ifaceStr) == ret.TypeStr {
					isConsumed = true
					break
				}
			}
		}
		// Also check for closeable — we need the var name for cleanup
		hasClose := isNilable(ret.Type) && checkCloseable(ret.Type, "_") != nil

		if !isConsumed && !hasClose {
			lhsNames = append(lhsNames, "_")
			continue
		}

		fieldName := FieldName(ret.TypeStr)
		varName := localVarName(fieldName)
		// Avoid shadowing import qualifiers
		if cg.imports.IsQualifier(varName) {
			varName = varName + "Svc"
		}
		// Ensure uniqueness
		origVarName := varName
		for i := 2; usedVars[varName]; i++ {
			varName = fmt.Sprintf("%s%d", origVarName, i)
		}
		usedVars[varName] = true
		lhsNames = append(lhsNames, varName)
		varMap[ret.TypeStr] = varName

		// Check for closeable
		if isNilable(ret.Type) {
			if cl := checkCloseable(ret.Type, varName); cl != nil {
				*closeables = append(*closeables, CloseableField{
					VarName: varName,
					Method:  cl.Method,
					HasCtx:  cl.HasCtx,
				})
			}
		}
	}

	if p.HasError {
		if len(lhsNames) > 0 {
			fmt.Fprintf(buf, "\t%s, err := %s(%s)\n", strings.Join(lhsNames, ", "), qualifier, strings.Join(args, ", "))
		} else {
			fmt.Fprintf(buf, "\t_, err := %s(%s)\n", qualifier, strings.Join(args, ", "))
		}
		fmt.Fprintf(buf, "\tif err != nil {\n")
		fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"%s.%s: %%w\", err)\n", p.PkgName, p.FuncName)
		fmt.Fprintf(buf, "\t}\n")
	} else {
		if len(lhsNames) > 0 {
			fmt.Fprintf(buf, "\t%s := %s(%s)\n", strings.Join(lhsNames, ", "), qualifier, strings.Join(args, ", "))
		} else {
			fmt.Fprintf(buf, "\t%s(%s)\n", qualifier, strings.Join(args, ", "))
		}
	}
}

// registerProviderImports pre-registers provider packages so local variable name
// generation can avoid import qualifier collisions.
func (cg *CodeGen) registerProviderImports(providers []*Provider) {
	for _, p := range providers {
		_ = cg.qualifyFunc(p)
	}
}

// uniqueLocalVar returns a unique local variable name that does not collide with
// existing locals or import qualifiers.
func (cg *CodeGen) uniqueLocalVar(base string, usedVars map[string]bool) string {
	if base == "" {
		base = "value"
	}

	name := base
	for i := 2; usedVars[name] || cg.imports.IsQualifier(name); i++ {
		name = fmt.Sprintf("%s%d", base, i)
	}
	usedVars[name] = true
	return name
}

// matchingSliceReturnIndexes returns provider return indexes that should be
// added to a []elemTypeStr slice.
func (cg *CodeGen) matchingSliceReturnIndexes(p *Provider, elemTypeStr string) ([]int, error) {
	if len(p.Returns) == 0 {
		return nil, fmt.Errorf("provider %s.%s has no return values", p.PkgName, p.FuncName)
	}

	resolvedElem := cg.graph.resolveConfigType(elemTypeStr)
	iface := cg.graph.findIfaceType(resolvedElem)

	var matches []int
	for i, ret := range p.Returns {
		if ret.TypeStr == resolvedElem || cg.graph.resolveType(ret.TypeStr) == resolvedElem {
			matches = append(matches, i)
			continue
		}
		if iface != nil {
			if cg.graph.cachedImplements(ret.Type, ret.TypeStr, iface, resolvedElem) {
				matches = append(matches, i)
				continue
			}
			if _, isPtr := ret.Type.(*types.Pointer); !isPtr {
				ptrType := types.NewPointer(ret.Type)
				ptrStr := "*" + ret.TypeStr
				if cg.graph.cachedImplements(ptrType, ptrStr, iface, resolvedElem) {
					matches = append(matches, i)
				}
			}
		}
	}

	if len(matches) == 0 {
		return nil, fmt.Errorf("provider %s.%s has no return matching %s", p.PkgName, p.FuncName, toShortTypeName(resolvedElem))
	}
	return matches, nil
}

// writeSliceProviderCalls emits provider calls that append the selected return
// value into the target slice variable.
func (cg *CodeGen) writeSliceProviderCalls(buf *bytes.Buffer, sliceVarName, elemTypeStr string, providers []*Provider, varMap map[string]string, usedVars map[string]bool) error {
	for _, p := range providers {
		matchIdxs, err := cg.matchingSliceReturnIndexes(p, elemTypeStr)
		if err != nil {
			return err
		}

		qualifier := cg.qualifyFunc(p)
		args := cg.buildLocalArgs(p, varMap)

		if len(p.Returns) == 1 && !p.HasError && len(matchIdxs) == 1 && matchIdxs[0] == 0 {
			fmt.Fprintf(buf, "\t%s = append(%s, %s(%s))\n", sliceVarName, sliceVarName, qualifier, strings.Join(args, ", "))
			continue
		}

		selectedVars := make(map[int]string, len(matchIdxs))
		for _, idx := range matchIdxs {
			selectedType := p.Returns[idx].TypeStr
			selectedVar := localVarName(FieldName(selectedType))
			if cg.imports.IsQualifier(selectedVar) {
				selectedVar = selectedVar + "Val"
			}
			selectedVars[idx] = cg.uniqueLocalVar(selectedVar, usedVars)
		}

		lhs := make([]string, 0, len(p.Returns)+1)
		for i := range p.Returns {
			if selectedVar, ok := selectedVars[i]; ok {
				lhs = append(lhs, selectedVar)
				continue
			}
			lhs = append(lhs, "_")
		}

		if p.HasError {
			lhs = append(lhs, "err")
			fmt.Fprintf(buf, "\t%s := %s(%s)\n", strings.Join(lhs, ", "), qualifier, strings.Join(args, ", "))
			fmt.Fprintf(buf, "\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"%s.%s: %%w\", err)\n", p.PkgName, p.FuncName)
			fmt.Fprintf(buf, "\t}\n")
		} else {
			fmt.Fprintf(buf, "\t%s := %s(%s)\n", strings.Join(lhs, ", "), qualifier, strings.Join(args, ", "))
		}

		for _, idx := range matchIdxs {
			fmt.Fprintf(buf, "\t%s = append(%s, %s)\n", sliceVarName, sliceVarName, selectedVars[idx])
		}
	}

	return nil
}

// buildLocalArgs constructs the argument list for a provider call using local vars.
func (cg *CodeGen) buildLocalArgs(p *Provider, varMap map[string]string) []string {
	var args []string
	for _, param := range p.Params {
		resolved := cg.graph.resolveType(param.TypeStr)
		if varName, ok := varMap[resolved]; ok {
			args = append(args, varName)
		} else if varName, ok := varMap[param.TypeStr]; ok {
			args = append(args, varName)
		} else {
			args = append(args, "nil /* missing: "+toShortTypeName(param.TypeStr)+" */")
		}
	}
	return args
}

// matchGroup checks if a type string matches a group definition.
// Returns the group name, or "" if not a group.
func (cg *CodeGen) matchGroup(typeStr string) string {
	if !strings.HasPrefix(typeStr, "[]") {
		return ""
	}
	elemType := typeStr[2:]

	for groupName, groupCfg := range cg.cfg.Groups {
		groupIfaceFull := cg.graph.resolveConfigType(groupCfg.Interface)
		if elemType == groupIfaceFull {
			return groupName
		}
	}
	return ""
}

// isTypeNeeded checks if a type is needed by the command or its group/auto-collected providers.
func (cg *CodeGen) isTypeNeeded(typeStr string, neededTypes []string, cmd *DiscoveredCommand) bool {
	for _, t := range neededTypes {
		if t == typeStr {
			return true
		}
	}
	// Check group provider params and auto-collected provider params
	for _, param := range cmd.Params {
		groupName := cg.matchGroup(param.TypeStr)
		if groupName != "" {
			for _, p := range cg.graph.Groups[groupName] {
				for _, dep := range p.Params {
					if dep.TypeStr == typeStr {
						return true
					}
				}
			}
		} else if strings.HasPrefix(param.TypeStr, "[]") {
			elemType := param.TypeStr[2:]
			autoProviders := cg.graph.AutoCollect(elemType)
			for _, p := range autoProviders {
				for _, dep := range p.Params {
					if dep.TypeStr == typeStr {
						return true
					}
				}
			}
		}
	}
	return false
}

// qualifyFunc returns the qualified function call like "iam.NewIAM".
func (cg *CodeGen) qualifyFunc(p *Provider) string {
	alias := cg.imports.Add(p.PkgPath, p.PkgName)
	if alias == "" {
		return p.FuncName
	}
	return alias + "." + p.FuncName
}

// qualifyType converts a type string (possibly short config name) into Go source.
func (cg *CodeGen) qualifyType(typeStr, _ string) string {
	resolved := cg.graph.resolveConfigType(typeStr)
	return cg.shortType(resolved)
}

// shortType converts a fully qualified type string to its short form,
// registering imports as needed.
func (cg *CodeGen) shortType(typeStr string) string {
	prefix := ""
	s := typeStr

	if strings.HasPrefix(s, "*") {
		prefix = "*"
		s = s[1:]
	}

	dotIdx := strings.LastIndex(s, ".")
	if dotIdx < 0 {
		return typeStr
	}

	pkgPath := s[:dotIdx]
	typeName := s[dotIdx+1:]

	if !strings.Contains(pkgPath, "/") {
		resolved := cg.graph.resolveConfigType(typeStr)
		if resolved != typeStr {
			return cg.shortType(resolved)
		}
		if fullPkg, ok := cg.graph.pkgNameToPath[pkgPath]; ok {
			pkgPath = fullPkg
		}
	}

	pkgName := pkgShortName(pkgPath)
	qualifier := cg.imports.Add(pkgPath, pkgName)
	return prefix + qualifier + "." + typeName
}
