package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// generateMermaid produces a Mermaid flowchart (TB) that visualises the full DI graph:
//   - Layout: top-to-bottom — leaf/foundation providers at top, commands at bottom.
//   - Arrows point in injection direction: Dependency --> Consumer.
//   - Providers are clustered in subgraphs by relative package path.
//   - Node labels show the provided type on the first line and constructor name on the second.
//   - Leaf providers (no params) are green; composed providers are blue; invoke are purple.
//   - Interface types appear as dedicated orange hexagon nodes in an "Interfaces" subgraph,
//     making DIP (dependency inversion) chains visible: Impl → Interface → Consumer.
//   - Decorator providers (implement + depend on same interface) are red.
//   - Commands are grouped in a "Commands" subgraph (dark nodes, stadium shape).
func generateMermaid(graph *Graph, commands []*DiscoveredCommand, cfg *Config) []byte {
	mg := &mermaidGen{
		graph:    graph,
		commands: commands,
		cfg:      cfg,
		ids:      make(map[string]string),
		usedIDs:  make(map[string]bool),
	}
	return mg.render()
}

type mermaidGen struct {
	graph    *Graph
	commands []*DiscoveredCommand
	cfg      *Config
	ids      map[string]string // providerKey → mermaid node ID
	usedIDs  map[string]bool
}

func (mg *mermaidGen) providerKey(p *Provider) string {
	return p.PkgPath + "::" + p.FuncName
}

// nodeID returns the stable Mermaid identifier for a provider, creating one on first use.
func (mg *mermaidGen) nodeID(p *Provider) string {
	key := mg.providerKey(p)
	if id, ok := mg.ids[key]; ok {
		return id
	}
	base := "P_" + sanitizeMermaidID(p.PkgName+"_"+p.FuncName)
	id := base
	for i := 2; mg.usedIDs[id]; i++ {
		id = fmt.Sprintf("%s_%d", base, i)
	}
	mg.ids[key] = id
	mg.usedIDs[id] = true
	return id
}

// ifaceNodeID returns a stable node ID for an interface type.
func (mg *mermaidGen) ifaceNodeID(typeStr string) string {
	short := toShortTypeName(typeStr)
	return "IF_" + sanitizeMermaidID(short)
}

func (mg *mermaidGen) render() []byte {
	var buf bytes.Buffer

	buf.WriteString("%% Generated by autodi — DO NOT EDIT\n")
	buf.WriteString("%% Requires Mermaid v10.0+ for hexagon {{...}} interface nodes\n")
	buf.WriteString("flowchart TB\n\n")

	// ── Style classes ─────────────────────────────────────────────────────────
	buf.WriteString("    classDef leaf      fill:#27ae60,stroke:#1e8449,color:#fff\n")
	buf.WriteString("    classDef provider  fill:#2980b9,stroke:#1a5276,color:#fff\n")
	buf.WriteString("    classDef invoke    fill:#8e44ad,stroke:#6c3483,color:#fff\n")
	buf.WriteString("    classDef command   fill:#2c3e50,stroke:#17202a,color:#fff\n")
	buf.WriteString("    classDef iface     fill:#e67e22,stroke:#d35400,color:#fff\n")
	buf.WriteString("    classDef decorator fill:#c0392b,stroke:#922b21,color:#fff\n")
	buf.WriteString("\n")

	// ── Collect interfaces and compute usage stats first ──────────────────────
	ifaceSet := mg.collectIfaceTypes()
	providerCounts, ifaceStats := mg.computeStats(ifaceSet)

	// ── Provider subgraphs: one per package ───────────────────────────────────
	pkgMap := make(map[string][]*Provider)
	for _, p := range mg.graph.Providers {
		pkgMap[p.PkgPath] = append(pkgMap[p.PkgPath], p)
	}
	pkgPaths := make([]string, 0, len(pkgMap))
	for pp := range pkgMap {
		pkgPaths = append(pkgPaths, pp)
	}
	sort.Strings(pkgPaths)

	buf.WriteString("    %% ── Providers ────────────────────────────────────────────────────────\n")
	for _, pkgPath := range pkgPaths {
		providers := pkgMap[pkgPath]
		rel := mermaidRelPkg(pkgPath, mg.cfg.Module)
		subID := "sg_" + sanitizeMermaidID(rel)
		fmt.Fprintf(&buf, "    subgraph %s[\"%s\"]\n", subID, rel)
		for _, p := range providers {
			id := mg.nodeID(p)
			label := mg.providerLabel(p, providerCounts[id])
			if p.IsInvoke {
				fmt.Fprintf(&buf, "        %s[[\"%s\"]]\n", id, label)
			} else {
				fmt.Fprintf(&buf, "        %s[\"%s\"]\n", id, label)
			}
		}
		buf.WriteString("    end\n\n")
	}

	// ── Interface nodes ───────────────────────────────────────────────────────
	if len(ifaceSet) > 0 {
		buf.WriteString("    %% ── Interfaces ───────────────────────────────────────────────────────\n")
		buf.WriteString("    subgraph sg_interfaces[\"Interfaces\"]\n")
		sortedIfaces := sortedStringKeys(ifaceSet)
		for _, ifaceTypeStr := range sortedIfaces {
			id := mg.ifaceNodeID(ifaceTypeStr)
			label := mermaidEscape(ifaceShortName(ifaceTypeStr))
			stat := ifaceStats[ifaceTypeStr]
			if stat[0] > 0 || stat[1] > 0 {
				label += fmt.Sprintf("<br/>%d impl · %d use", stat[0], stat[1])
			}
			fmt.Fprintf(&buf, "        %s{{\"«interface»<br/>%s\"}}\n", id, label)
		}
		buf.WriteString("    end\n\n")

		// Implements edges: Concrete -.->|implements| Interface (rendered once per pair)
		buf.WriteString("    %% ── Implements ───────────────────────────────────────────────────────\n")
		rendered := make(map[string]bool)
		for _, ifaceTypeStr := range sortedIfaces {
			ifaceID := mg.ifaceNodeID(ifaceTypeStr)
			mg.writeImplementsEdges(&buf, ifaceTypeStr, ifaceID, rendered)
		}
		buf.WriteString("\n")
	}

	// ── Commands subgraph ─────────────────────────────────────────────────────
	if len(mg.commands) > 0 {
		buf.WriteString("    %% ── Commands ─────────────────────────────────────────────────────────\n")
		buf.WriteString("    subgraph sg_commands[\"Commands\"]\n")
		for _, cmd := range mg.commands {
			cmdID := "C_" + sanitizeMermaidID(cmd.Name)
			fmt.Fprintf(&buf, "        %s([\"⚡ %s\"])\n", cmdID, mg.commandLabel(cmd))
		}
		buf.WriteString("    end\n\n")
		for _, cmd := range mg.commands {
			cmdID := "C_" + sanitizeMermaidID(cmd.Name)
			fmt.Fprintf(&buf, "    class %s command\n", cmdID)
		}
		buf.WriteString("\n")
	}

	// ── Dependency edges ──────────────────────────────────────────────────────
	// Arrows go: Dependency --> Consumer (injection direction).
	// Interface deps are routed through the interface node.
	buf.WriteString("    %% ── Dependencies ─────────────────────────────────────────────────────\n")
	for _, p := range mg.graph.Providers {
		mg.writeParamEdges(&buf, mg.nodeID(p), p.Params, ifaceSet)
	}
	for _, cmd := range mg.commands {
		cmdID := "C_" + sanitizeMermaidID(cmd.Name)
		mg.writeParamEdges(&buf, cmdID, cmd.Params, ifaceSet)
	}
	buf.WriteString("\n")

	// ── Class assignments ─────────────────────────────────────────────────────
	buf.WriteString("    %% ── Styles ──────────────────────────────────────────────────────────\n")
	for _, p := range mg.graph.Providers {
		id := mg.nodeID(p)
		switch {
		case p.IsInvoke:
			fmt.Fprintf(&buf, "    class %s invoke\n", id)
		case mg.isDecorator(p):
			fmt.Fprintf(&buf, "    class %s decorator\n", id)
		case len(p.Params) == 0:
			fmt.Fprintf(&buf, "    class %s leaf\n", id)
		default:
			fmt.Fprintf(&buf, "    class %s provider\n", id)
		}
	}
	// Interface nodes
	for ifaceTypeStr := range ifaceSet {
		fmt.Fprintf(&buf, "    class %s iface\n", mg.ifaceNodeID(ifaceTypeStr))
	}

	return buf.Bytes()
}

// ── Interface collection ──────────────────────────────────────────────────────

// collectIfaceTypes gathers all interface types that are resolved through bindings
// or auto-collected as slice elements.
func (mg *mermaidGen) collectIfaceTypes() map[string]bool {
	ifaceSet := make(map[string]bool)

	collect := func(params []TypeRef) {
		for _, param := range params {
			if strings.HasPrefix(param.TypeStr, "[]") {
				elemType := param.TypeStr[2:]
				// Check groups
				if mg.matchGroupByElem(elemType) != "" {
					ifaceSet[elemType] = true
					continue
				}
				// Check auto-collect
				if len(mg.graph.AutoCollect(elemType)) > 0 {
					ifaceSet[elemType] = true
				}
			} else if param.IsIface {
				resolved := mg.graph.resolveType(param.TypeStr)
				if resolved != param.TypeStr {
					ifaceSet[param.TypeStr] = true
				}
			}
		}
	}

	for _, p := range mg.graph.Providers {
		collect(p.Params)
	}
	for _, cmd := range mg.commands {
		collect(cmd.Params)
	}
	return ifaceSet
}

// computeStats counts:
//   - providerCounts[nodeID]: how many providers/commands inject this provider
//   - ifaceStats[ifaceTypeStr]: [0]=impl count (concrete types), [1]=consumer count
func (mg *mermaidGen) computeStats(ifaceSet map[string]bool) (providerCounts map[string]int, ifaceStats map[string][2]int) {
	providerCounts = make(map[string]int)
	ifaceStats = make(map[string][2]int)

	// Impl counts: how many concrete types implement each interface.
	// Mirrors the dedup logic in writeImplementsEdges.
	for ifaceTypeStr := range ifaceSet {
		var count [2]int
		seen := make(map[string]bool)
		if concrete, ok := mg.graph.Bindings[ifaceTypeStr]; ok {
			if dep := mg.graph.ProviderMap[concrete]; dep != nil {
				key := mg.nodeID(dep)
				if !seen[key] {
					seen[key] = true
					count[0]++
				}
			}
		}
		for _, p := range mg.graph.AutoCollect(ifaceTypeStr) {
			key := mg.nodeID(p)
			if !seen[key] {
				seen[key] = true
				count[0]++
			}
		}
		for groupName, gc := range mg.cfg.Groups {
			if ifaceTypeStr == mg.graph.resolveConfigType(gc.Interface) {
				for _, gp := range mg.graph.Groups[groupName] {
					key := mg.nodeID(gp)
					if !seen[key] {
						seen[key] = true
						count[0]++
					}
				}
			}
		}
		ifaceStats[ifaceTypeStr] = count
	}

	// Consumer counts: walk every provider/command's param list.
	countConsumers := func(params []TypeRef) {
		for _, param := range params {
			if strings.HasPrefix(param.TypeStr, "[]") {
				elemType := param.TypeStr[2:]
				if ifaceSet[elemType] {
					// Slice of interface → interface consumer count
					s := ifaceStats[elemType]
					s[1]++
					ifaceStats[elemType] = s
				} else if groupName := mg.matchGroupByElem(elemType); groupName != "" {
					for _, gp := range mg.graph.Groups[groupName] {
						providerCounts[mg.nodeID(gp)]++
					}
				} else {
					for _, ap := range mg.graph.AutoCollect(elemType) {
						providerCounts[mg.nodeID(ap)]++
					}
				}
				continue
			}

			resolved := mg.graph.resolveType(param.TypeStr)
			dep := mg.graph.ProviderMap[resolved]
			if dep == nil {
				dep = mg.graph.ProviderMap[param.TypeStr]
			}
			if dep == nil {
				continue
			}
			if param.IsIface && ifaceSet[param.TypeStr] {
				s := ifaceStats[param.TypeStr]
				s[1]++
				ifaceStats[param.TypeStr] = s
			} else {
				providerCounts[mg.nodeID(dep)]++
			}
		}
	}
	for _, p := range mg.graph.Providers {
		countConsumers(p.Params)
	}
	for _, cmd := range mg.commands {
		countConsumers(cmd.Params)
	}
	return
}

// writeImplementsEdges emits "Concrete -.->|implements| Interface" edges for
// all providers that implement the given interface.
func (mg *mermaidGen) writeImplementsEdges(buf *bytes.Buffer, ifaceTypeStr, ifaceID string, rendered map[string]bool) {
	emit := func(dep *Provider) {
		key := mg.nodeID(dep) + "|" + ifaceID
		if rendered[key] {
			return
		}
		rendered[key] = true
		fmt.Fprintf(buf, "    %s -.->|implements| %s\n", mg.nodeID(dep), ifaceID)
	}

	// From explicit bindings
	if concrete, ok := mg.graph.Bindings[ifaceTypeStr]; ok {
		if dep := mg.graph.ProviderMap[concrete]; dep != nil {
			emit(dep)
		}
	}

	// From auto-collect
	for _, p := range mg.graph.AutoCollect(ifaceTypeStr) {
		emit(p)
	}

	// From groups
	for groupName, gc := range mg.cfg.Groups {
		if ifaceTypeStr == mg.graph.resolveConfigType(gc.Interface) {
			for _, gp := range mg.graph.Groups[groupName] {
				emit(gp)
			}
		}
	}
}

// ── Dependency edge rendering ─────────────────────────────────────────────────

// writeParamEdges emits Mermaid edges in injection direction.
// When an interface has a dedicated node (in ifaceSet), the edge is routed through it
// instead of going directly from concrete to consumer.
func (mg *mermaidGen) writeParamEdges(buf *bytes.Buffer, consumerID string, params []TypeRef, ifaceSet map[string]bool) {
	for _, param := range params {
		if strings.HasPrefix(param.TypeStr, "[]") {
			elemType := param.TypeStr[2:]
			sliceLabel := mermaidEscape("[]" + briefTypeName(elemType))

			if ifaceSet[elemType] {
				// Route through interface node: IFace --> Consumer
				ifaceID := mg.ifaceNodeID(elemType)
				fmt.Fprintf(buf, "    %s -.->|\"%s\"| %s\n", ifaceID, sliceLabel, consumerID)
			} else {
				// No interface node — fan out directly
				if groupName := mg.matchGroupByElem(elemType); groupName != "" {
					for _, gp := range mg.graph.Groups[groupName] {
						fmt.Fprintf(buf, "    %s -.->|\"%s\"| %s\n", mg.nodeID(gp), sliceLabel, consumerID)
					}
				} else {
					for _, ap := range mg.graph.AutoCollect(elemType) {
						fmt.Fprintf(buf, "    %s -.->|\"%s\"| %s\n", mg.nodeID(ap), sliceLabel, consumerID)
					}
				}
			}
			continue
		}

		resolved := mg.graph.resolveType(param.TypeStr)
		dep := mg.graph.ProviderMap[resolved]
		if dep == nil {
			dep = mg.graph.ProviderMap[param.TypeStr]
		}
		if dep == nil {
			continue
		}

		if param.IsIface && ifaceSet[param.TypeStr] {
			// Route through interface node: IFace --> Consumer
			ifaceID := mg.ifaceNodeID(param.TypeStr)
			fmt.Fprintf(buf, "    %s --> %s\n", ifaceID, consumerID)
		} else if param.IsIface && resolved != param.TypeStr {
			// Interface resolved but no dedicated node (shouldn't happen normally)
			depID := mg.nodeID(dep)
			shortIface := ifaceShortName(param.TypeStr)
			fmt.Fprintf(buf, "    %s -..->|\"%s\"| %s\n", depID, mermaidEscape(shortIface), consumerID)
		} else {
			depID := mg.nodeID(dep)
			fmt.Fprintf(buf, "    %s --> %s\n", depID, consumerID)
		}
	}
}

// ── Decorator detection ───────────────────────────────────────────────────────

// isDecorator detects the decorator/aspect pattern: a provider that is bound to an
// interface AND also takes that same interface as a parameter.
func (mg *mermaidGen) isDecorator(p *Provider) bool {
	if len(p.Returns) == 0 {
		return false
	}
	// Interfaces this provider's return type is bound to
	boundIfaces := make(map[string]bool)
	for iface, concrete := range mg.graph.Bindings {
		for _, ret := range p.Returns {
			if concrete == ret.TypeStr {
				boundIfaces[iface] = true
			}
		}
	}
	// Check if any param is one of those interfaces
	for _, param := range p.Params {
		if param.IsIface && boundIfaces[param.TypeStr] {
			return true
		}
	}
	return false
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// matchGroupByElem returns the group name whose interface element type matches elemType.
func (mg *mermaidGen) matchGroupByElem(elemType string) string {
	for groupName, gc := range mg.cfg.Groups {
		if elemType == mg.graph.resolveConfigType(gc.Interface) {
			return groupName
		}
	}
	return ""
}

// providerLabel produces a two-line label: the provided type on the first line,
// the constructor name on the second. Invoke providers show only the function name.
// depCount > 0 appends a third line "→ N" showing how many others inject this provider.
func (mg *mermaidGen) providerLabel(p *Provider, depCount int) string {
	suffix := ""
	if depCount > 0 {
		suffix = fmt.Sprintf("<br/>→ %d", depCount)
	}
	if p.IsInvoke || len(p.Returns) == 0 {
		return mermaidEscape(p.FuncName) + suffix
	}
	mainType := ""
	for _, ret := range p.Returns {
		if ret.TypeStr != "error" {
			mainType = briefTypeName(ret.TypeStr)
			break
		}
	}
	if mainType == "" {
		return mermaidEscape(p.FuncName) + suffix
	}
	return mermaidEscape(mainType) + "<br/>" + mermaidEscape(p.FuncName) + suffix
}

// briefTypeName strips the package path and keeps only the bare type name.
func briefTypeName(typeStr string) string {
	if strings.HasPrefix(typeStr, "[]") {
		return "[]" + briefTypeName(typeStr[2:])
	}
	prefix := ""
	s := typeStr
	if strings.HasPrefix(s, "*") {
		prefix = "*"
		s = s[1:]
	}
	if dot := strings.LastIndex(s, "."); dot >= 0 {
		return prefix + s[dot+1:]
	}
	return prefix + s
}

// commandLabel produces a two-line label for a command node.
func (mg *mermaidGen) commandLabel(cmd *DiscoveredCommand) string {
	name := mermaidEscape(cmd.Name)
	var methods []string
	for _, h := range cmd.Handlers {
		methods = append(methods, h.MethodName)
	}
	if len(methods) > 0 && len(methods) <= 4 {
		return name + "<br/>" + mermaidEscape(strings.Join(methods, " | "))
	}
	return name
}

// sanitizeMermaidID converts an arbitrary string to a valid Mermaid node identifier.
func sanitizeMermaidID(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// mermaidRelPkg returns the relative package path within the module.
func mermaidRelPkg(pkgPath, module string) string {
	rel := strings.TrimPrefix(pkgPath, module+"/")
	if rel == pkgPath {
		return pkgShortName(pkgPath)
	}
	return rel
}

// ifaceShortName extracts just the type name from a full interface type string.
func ifaceShortName(typeStr string) string {
	short := toShortTypeName(typeStr)
	if dot := strings.LastIndex(short, "."); dot >= 0 {
		return short[dot+1:]
	}
	return short
}

// mermaidEscape replaces characters that break Mermaid label parsing.
func mermaidEscape(s string) string {
	s = strings.ReplaceAll(s, "\"", "#quot;")
	return s
}

// sortedStringKeys returns sorted keys from a map[string]bool.
func sortedStringKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
