// Code generated by autodi, DO NOT EDIT.

package main

import (
	"fmt"
	migratecmd "github.com/iVampireSP/go-template/cmd/migrate"
	servecmd "github.com/iVampireSP/go-template/cmd/serve"
	usercmd "github.com/iVampireSP/go-template/cmd/user"
	versioncmd "github.com/iVampireSP/go-template/cmd/version"
	"github.com/iVampireSP/go-template/internal/api/admin/v1/handler"
	"github.com/iVampireSP/go-template/internal/api/admin/v1/route"
	v1handler "github.com/iVampireSP/go-template/internal/api/user/v1/handler"
	v1route "github.com/iVampireSP/go-template/internal/api/user/v1/route"
	wellknownhandler "github.com/iVampireSP/go-template/internal/api/wellknown/handler"
	"github.com/iVampireSP/go-template/internal/infra/cache"
	"github.com/iVampireSP/go-template/internal/infra/jwt"
	"github.com/iVampireSP/go-template/internal/infra/keystore"
	"github.com/iVampireSP/go-template/internal/infra/orm"
	"github.com/iVampireSP/go-template/internal/service/identity/admin"
	"github.com/iVampireSP/go-template/internal/service/identity/user"
	"github.com/spf13/cobra"
	"os"
	"strings"
)

func main() {
	root := &cobra.Command{Use: "app", Short: "App", Long: "Go Project Template"}

	type initFunc func(cmd, top *cobra.Command) (func(), error)
	initFuncs := make(map[*cobra.Command]initFunc)

	{
		stub := migratecmd.NewMigrate(nil)
		tree := stub.Command()
		wireRunE(tree, "down", stub.Down)
		wireRunE(tree, "fresh", stub.Fresh)
		wireRunE(tree, "status", stub.Status)
		wireRunE(tree, "up", stub.Up)
		root.AddCommand(tree)
		initFuncs[tree] = initMigrate
	}
	{
		stub := servecmd.NewServe(nil, nil, nil, nil, nil)
		tree := stub.Command()
		wireRunE(tree, "admin", stub.Admin)
		wireRunE(tree, "api", stub.Api)
		root.AddCommand(tree)
		initFuncs[tree] = initServe
	}
	{
		stub := usercmd.NewUser(nil)
		tree := stub.Command()
		wireRunE(tree, "create", stub.Create)
		root.AddCommand(tree)
		initFuncs[tree] = initUser
	}
	{
		stub := versioncmd.NewVersion()
		cmd := stub.Command()
		cmd.RunE = func(c *cobra.Command, _ []string) error { return stub.Handle(c) }
		root.AddCommand(cmd)
	}

	var cleanup func()
	root.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		top := cmd
		for top.HasParent() && top.Parent().HasParent() {
			top = top.Parent()
		}
		if fn, ok := initFuncs[top]; ok {
			var err error
			cleanup, err = fn(cmd, top)
			return err
		}
		return nil
	}
	root.PersistentPostRunE = func(cmd *cobra.Command, args []string) error {
		if cleanup != nil {
			cleanup()
		}
		return nil
	}

	if err := root.Execute(); err != nil {
		os.Exit(1)
	}
}

func initMigrate(cmd, top *cobra.Command) (func(), error) {
	redisUniversalClient, cacheLocker := cache.New()

	real := migratecmd.NewMigrate(cacheLocker)
	tree := real.Command()
	wireRunE(tree, "down", real.Down)
	wireRunE(tree, "fresh", real.Fresh)
	wireRunE(tree, "status", real.Status)
	wireRunE(tree, "up", real.Up)
	swapRunE(cmd, top, tree)

	return func() {
		if redisUniversalClient != nil {
			redisUniversalClient.Close()
		}
	}, nil
}

func initServe(cmd, top *cobra.Command) (func(), error) {
	entClient := orm.NewORM()

	keyStore, err := keystore.NewKeyStore()
	if err != nil {
		return nil, fmt.Errorf("keystore.NewKeyStore: %w", err)
	}

	jwtSvc, err := jwt.NewJWT(keyStore)
	if err != nil {
		return nil, fmt.Errorf("jwt.NewJWT: %w", err)
	}

	adminSvc := admin.NewAdmin(jwtSvc)

	redisUniversalClient, cacheLocker := cache.New()

	handlerAuthHandler := handler.NewAuthHandler(adminSvc, redisUniversalClient)

	userSvc := user.NewUser(entClient, jwtSvc, cacheLocker, redisUniversalClient)

	handlerUserHandler := handler.NewUserHandler(userSvc)

	routeAuth := route.NewAuth(handlerAuthHandler)

	routeUser := route.NewUser(handlerUserHandler)

	router := route.NewRouter(adminSvc, routeAuth, routeUser)

	handlerAuthHandler2 := v1handler.NewAuthHandler(userSvc, redisUniversalClient)

	handlerProfileHandler := v1handler.NewProfileHandler(userSvc)

	routeAuth2 := v1route.NewAuth(handlerAuthHandler2)

	routeProfile := v1route.NewProfile(handlerProfileHandler)

	router2 := v1route.NewRouter(userSvc, routeAuth2, routeProfile)

	handlerJWKSHandler := wellknownhandler.NewJWKSHandler(jwtSvc)

	handlerDiscoveryHandler := wellknownhandler.NewDiscoveryHandler(handlerJWKSHandler)

	real := servecmd.NewServe(jwtSvc, handlerJWKSHandler, handlerDiscoveryHandler, router, router2)
	tree := real.Command()
	wireRunE(tree, "admin", real.Admin)
	wireRunE(tree, "api", real.Api)
	swapRunE(cmd, top, tree)

	return func() {
		if redisUniversalClient != nil {
			redisUniversalClient.Close()
		}
		if entClient != nil {
			entClient.Close()
		}
	}, nil
}

func initUser(cmd, top *cobra.Command) (func(), error) {
	entClient := orm.NewORM()

	redisUniversalClient, cacheLocker := cache.New()

	keyStore, err := keystore.NewKeyStore()
	if err != nil {
		return nil, fmt.Errorf("keystore.NewKeyStore: %w", err)
	}

	jwtSvc, err := jwt.NewJWT(keyStore)
	if err != nil {
		return nil, fmt.Errorf("jwt.NewJWT: %w", err)
	}

	userSvc := user.NewUser(entClient, jwtSvc, cacheLocker, redisUniversalClient)

	real := usercmd.NewUser(userSvc)
	tree := real.Command()
	wireRunE(tree, "create", real.Create)
	swapRunE(cmd, top, tree)

	return func() {
		if redisUniversalClient != nil {
			redisUniversalClient.Close()
		}
		if entClient != nil {
			entClient.Close()
		}
	}, nil
}

// wireRunE connects a handler method to a subcommand's RunE by kebab-case name.
// For nested commands, the name segments form a path (e.g. "pool-list" matches pool→list).
func wireRunE(parent *cobra.Command, name string, handler func(*cobra.Command) error) {
	// Try exact match first (direct child)
	for _, sub := range parent.Commands() {
		if sub.Name() == name {
			h := handler
			sub.RunE = func(cmd *cobra.Command, _ []string) error { return h(cmd) }
			return
		}
	}
	// Try path-based match: split name by "-" and greedily match child commands
	parts := strings.Split(name, "-")
	wireRunEPath(parent, parts, handler)
}

func wireRunEPath(parent *cobra.Command, parts []string, handler func(*cobra.Command) error) bool {
	if len(parts) == 0 {
		return false
	}
	// Try progressively longer prefixes as the child command name
	for i := 1; i <= len(parts); i++ {
		candidate := strings.Join(parts[:i], "-")
		for _, sub := range parent.Commands() {
			if sub.Name() != candidate {
				continue
			}
			if i == len(parts) {
				// Leaf match
				h := handler
				sub.RunE = func(cmd *cobra.Command, _ []string) error { return h(cmd) }
				return true
			}
			// Try remaining parts as deeper path
			if wireRunEPath(sub, parts[i:], handler) {
				return true
			}
		}
	}
	return false
}

// swapRunE replaces the executing command's RunE with the real one from the DI-built tree.
func swapRunE(executing, stubTop, realTop *cobra.Command) {
	path := relativePath(executing, stubTop)
	target := realTop
	for _, name := range path {
		for _, sub := range target.Commands() {
			if sub.Name() == name {
				target = sub
				break
			}
		}
	}
	executing.RunE = target.RunE
}

func relativePath(cmd, ancestor *cobra.Command) []string {
	if cmd == ancestor {
		return nil
	}
	return append(relativePath(cmd.Parent(), ancestor), cmd.Name())
}
