app:
  name: template
  allowed_audiences:
    - "1" # UserLand Personal Access Client

http:
  port: 8080
  host: 0.0.0.0
  # the production url
  url: http://127.0.0.1:8080
  cors:
    enabled: true
    allow_origins:
      - "http://localhost:8080"
    allow_methods:
      - "GET"
      - "HEAD"
      - "PUT"
      - "PATCH"
      - "POST"
      - "DELETE"
    allow_headers:
      - "Origin"
      - "Content-Length"
      - "Content-Type"
      - "X-Requested-With"
      - "Authorization"
    allow_credentials: true
    expose_headers: [ ]
    max_age: 720

grpc:
  address: 0.0.0.0:9090
  address_gateway: 0.0.0.0:9091

debug:
  enabled: false

database:
  host: 127.0.0.1
  port: 5432
  user: root
  password: root
  name: db_name
  sslmode: disable
  timezone: "Asia/Shanghai"

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwks:
  url: "https://auth.leaflow.cn/.well-known/jwks"

metrics:
  enabled: true
  port: 8081
  host: 0.0.0.0

s3:
  endpoint: 127.0.0.1:9000
  external_endpoint: 127.0.0.1:9000
  access_key: minio
  secret_key: minio123
  bucket: amber
  use_ssl: false
  region:


kafka:
  bootstrap_servers:
    - 127.0.0.1:9092
  topic: "amber"
  group_id: ""
  # Plain
  username: ""
  password: ""

milvus:
  host: 127.0.0.1
  port: 19530
  db_name: library
  document_collection: documents
  user:
  password:

third_party:
  openai_api_key: ""